before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
