fail_fast: false
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-build
      - id: go-fmt
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: go-critic
      - id: go-unit-tests
      - id: go-lint
      - id: golangci-lint
        args:
          - -c .golangci.yml
          - -E staticcheck
