language: go

branches:
  only: # speed up CI: don't build pull requests twice
    - "master"
    - /^v\d+\.\d+\.\d+$/

go:
  - "1.14.2"

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

jobs:
  include:
    - script: go test -v ./...
    - stage: lint
      script: golangci-lint run -c .golangci.yml ./...
    - stage: goreleaser_check
      script: curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations
    - stage: tag
      script: |
        npm i -g standard-version
        standard-version

stages:
  - test
  - lint
  - goreleaser_check
  - name: tag
    if: NOT type IN (pull_request) AND branch = master

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.24.0

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
